#!/bin/bash
sudo systemctl stop firewalld
printf "installing httpd 7777777777777777 \n"
sudo yum install -y httpd
sudo systemctl start httpd
printf "\n starting httpd 7777777777777777 \n"
sudo systemctl enable httpd
echo "<h1>Deployed via Terraform</h1>" | sudo tee /var/www/html/index.html
sleep 20s
